### ISSUE TITLE
Feature request: check Github Action files too (not just Github Workflow files)

### ISSUE THREAD

**Issue by lukaw3d** [mschuett/yaml-shellcheck#11]
https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action#creating-an-action-metadata-file

Naive implementation: https://github.com/lukaw3d/yaml-shellcheck/commit/48e1ccccc2d5675be4939534ab7acf685be3ff98
I don't know if this conflicts with any other format; and it checks if `inputs` field exists, even tho it is optional

**Comment by mschuett** [comment]
implemented in the PR and released as part of [v1.4.0](https://github.com/mschuett/yaml-shellcheck/releases/tag/v1.4.0)
