### ISSUE TITLE
Support !reference with any number of elements

### ISSUE THREAD

**Issue by mrijken** [mschuett/yaml-shellcheck#17]
We use yaml_shellcheck to check our gitlab yaml files. We use !reference with 1 and 2 elements. Gitlab happily parses both. yaml_shellcheck parses only 2 elements and gives a ruamel.yaml parse error with 1 element in the !reference tag. Are you open for a PR to fix this?

**Comment by mrijken** [comment]
According to git@github.com:mschuett/yaml-shellcheck.git any sequence is valid. There is no requirement for 2 elements. I suggest tot support any number of elements.

**Comment by mschuett** [comment]
Thank you for the issue & the PR!

I was not even aware the number of elements is variable :-)
